 version: '3'
 services:
  loki:
    image: grafana/loki:3.1.0
    user: root
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yaml
    volumes:
     - ./config/loki.yml:/etc/loki/config.yaml 
     - ./data/loki:/data/loki
    networks:
     - monitoringy
  prometheus:
      image: prom/prometheus:v2.53.1
      user: root
      container_name: prometheus
      restart: unless-stopped
      volumes:
        - ./data/prometheus/config:/etc/prometheus/
        - ./data/prometheus/data:/prometheus
        - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--web.enable-remote-write-receiver'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.enable-lifecycle'
      ports:
        - 9090:9090
      networks:
        - monitoring